#include "iggy.h"
#include "stdbool.h"
#include "stdint.h"
#include "stub.h"
// STUBBED(IggyPlayerCallbackResultPath);
// STUBBED(IggyPlayerCallFunctionRS);
STUBBED(IggyPlayerCallFunctionRS_core);
// STUBBED(IggyPlayerCallMethodRS);
STUBBED(IggyPlayerCallMethodRS_core);
// STUBBED(IggyPlayerConfigureGCBehavior);
// STUBBED(IggyPlayerCopyUTF16);
// STUBBED(IggyPlayerCopyUTF8);
// STUBBED(IggyPlayerCreateFastName);
// STUBBED(IggyPlayerCreateFastNameUTF8);
// STUBBED(IggyPlayerCreateFromFileAndPlay);
STUBBED(IggyPlayerCreateFromFileAndPlay_core);
// STUBBED(IggyPlayerCreateFromMemory);
// STUBBED(IggyPlayerCut);
STUBBED(IggyPlayerCut_core);
// STUBBED(IggyPlayerDebugBatchChooseEnd);
STUBBED(IggyPlayerDebugBatchInit);
// STUBBED(IggyPlayerDebugBatchMove);
STUBBED(IggyPlayerDebugBatchSplit);
STUBBED(IggyPlayerDebugBatchStartFrame);
// STUBBED(IggyPlayerDebugEnableFilters);
// STUBBED(IggyPlayerDebugSetTime);
// STUBBED(IggyPlayerDebugUpdateReadyToTickWithFakeRender);
// STUBBED(IggyPlayerDestroy);
STUBBED(IggyPlayerDisableFaux3DStage);
// STUBBED(IggyPlayerDispatchEventRS);
STUBBED(IggyPlayerDispatchEventRS_core);
STUBBED(IggyPlayerDoubleClickTime);
// STUBBED(IggyPlayerDraw);
STUBBED(IggyPlayerDraw_core);
// STUBBED(IggyPlayerDrawTile);
STUBBED(IggyPlayerDrawTile_core);
// STUBBED(IggyPlayerDrawTilesEnd);
STUBBED(IggyPlayerDrawTilesEnd_core);
// STUBBED(IggyPlayerDrawTilesStart);
// STUBBED(IggyPlayerFlushAll);
// STUBBED(IggyPlayerGarbageCollect);
STUBBED(IggyPlayerGarbageCollect_core);
// STUBBED(IggyPlayerGetBackgroundColor);
// STUBBED(IggyPlayerGetFocusableObjects);
// STUBBED(IggyPlayerGetGeneric);
// STUBBED(IggyPlayerGetUserdata);
// STUBBED(IggyPlayerGetValid);
// STUBBED(IggyPlayerGotoFrameRS);
STUBBED(IggyPlayerGotoFrameRS_core);
// STUBBED(IggyPlayerHasFocusedEditableTextfield);
// STUBBED(IggyPlayerInitializeAndTickRS);
STUBBED(IggyPlayerInitializeAndTickRS_core);
// STUBBED(IggyPlayerPasteUTF16);
STUBBED(IggyPlayerPasteUTF16_core);
// STUBBED(IggyPlayerPasteUTF8);
STUBBED(IggyPlayerPasteUTF8_core);
// STUBBED(IggyPlayerPause);
// STUBBED(IggyPlayerPlay);
// STUBBED(IggyPlayerProperties);
// STUBBED(IggyPlayerQueryGCSizes);
// STUBBED(IggyPlayerReadyToTick);
// STUBBED(IggyPlayerRootPath);
// STUBBED(IggyPlayerSendFrameToExplorer);
// STUBBED(IggyPlayerSetAntialiasing);
// STUBBED(IggyPlayerSetAudioDevice);
// STUBBED(IggyPlayerSetAudioVolume);
// STUBBED(IggyPlayerSetBitmapFontCaching);
// STUBBED(IggyPlayerSetDisplaySize);
// STUBBED(IggyPlayerSetFaux3DStage);
// STUBBED(IggyPlayerSetFocus_core);
// STUBBED(IggyPlayerSetFocusRS);
// STUBBED(IggyPlayerSetFrameRate);
// STUBBED(IggyPlayerSetIMEFontUTF16);
// STUBBED(IggyPlayerSetIMEFontUTF8);
// STUBBED(IggyPlayerSetPixelShape);
// STUBBED(IggyPlayerSetRootTransform);
// STUBBED(IggyPlayerSetShiftState);
// STUBBED(IggyPlayerSetStageRotation);
STUBBED(IggyPlayerSetStageRotation_core);
// STUBBED(IggyPlayerSetStageSize);
// STUBBED(IggyPlayerSetUserdata);
// STUBBED(IggyPlayerTickRS);
STUBBED(IggyPlayerTickRS_core);
STUBBED(iggy_API_begin);
STUBBED(iggy_API_end);
STUBBED(iggy_API_getset_begin);
STUBBED(iggy_API_getset_end);
