#include "iggy.h"
#include "stub.h"
STUBBED(iggy_font_init_bitmap_font);
STUBBED(iggy_font_initialize_cached_metrics);
STUBBED(iggy_font_init_swf_definefont);
STUBBED(iggy_font_init_vector_font);
STUBBED(iggy_free_all_device_fonts);
STUBBED(iggy_free_all_font_indirections);
STUBBED(iggy_get_font_metrics);
STUBBED(iggy_tt_GetFontBoundingBox);
STUBBED(iggy_tt_GetFontNameString);
STUBBED(iggy_tt_GetFontOffsetForIndex);
STUBBED(iggy_tt_GetFontVMetrics);
STUBBED(iggy_tt_InitFont);
STUBBED(IggyFlushInstalledFonts);
// STUBBED(IggyFontInstallBitmapOverrideUTF16);
// STUBBED(IggyFontInstallBitmapOverrideUTF8);
// STUBBED(IggyFontInstallBitmapUTF16);
// STUBBED(IggyFontInstallBitmapUTF8);
// STUBBED(IggyFontInstallTruetypeFallbackCodepointUTF16);
// STUBBED(IggyFontInstallTruetypeFallbackCodepointUTF8);
// STUBBED(IggyFontInstallTruetypeUTF16);
// STUBBED(IggyFontInstallTruetypeUTF8);
// STUBBED(IggyFontInstallVectorUTF16);
// STUBBED(IggyFontInstallVectorUTF8);
// STUBBED(IggyFontRemoveUTF16);
// STUBBED(IggyFontRemoveUTF8);
// STUBBED(IggyFontSetFallbackFontUTF16);
// STUBBED(IggyFontSetFallbackFontUTF8);
// STUBBED(IggyFontSetIndirectUTF16);
// STUBBED(IggyFontSetIndirectUTF8);
// STUBBED(iggy_get_fallback_font);
STUBBED(iggy_initialize_device_fonts);
STUBBED(iggy_resolve_indirect_font);
// STUBBED(IggySetFontCachingCalculationBuffer);
// STUBBED(IggySetIndirectFontMaxCount);
// STUBBED(IggySetInstalledFontMaxCount);
STUBBED(iggy_tt_BakeFontBitmap);
STUBBED(iggy_tt_FindMatchingFont);
