#include "iggy.h"
#include "rrCore.h"
#include "stdarg.h"
#include "stub.h"
#define DEBUG 1
STUBBED(iggy_abandon_direct_textures);
STUBBED(iggy_add_framescript);
STUBBED(iggy_add_library);
STUBBED(iggy_add_movie_framescript);
STUBBED(iggy_add_sound_client);
STUBBED(iggy_add_to_unparented);
STUBBED(iggy_advance_movie_GC);
STUBBED(iggy_advance_movie_raw_GC);
STUBBED(iggy_ail_fetch);
// STUBBED(IggyAudioInstallMP3DecoderExplicit);
STUBBED(iggy_audio_update);
STUBBED(IggyAudioUseDefault);
STUBBED(IggyAudioUseOpenAL);
STUBBED(iggy_begin_execution);
STUBBED(iggy_build_scene_lists_for_library);
STUBBED(iggy_button_draw_child_index);
STUBBED(iggy_button_mouse_child_index);
STUBBED(iggy_callback_begin);
STUBBED(iggy_callback_end);
STUBBED(iggy_change_sample);
STUBBED(iggy_check_caches);
STUBBED(iggy_check_display_trees);
STUBBED(iggy_clamp_to_s16);
STUBBED(iggy_clamp_to_s16_interleave_2_4);
STUBBED(iggy_clamp_to_u8);
STUBBED(iggy_clear_active_bits);
STUBBED(iggy_clear_movie_dirty);
STUBBED(iggy_clear_renderstate);
STUBBED(iggyCompareUTF8toUTF16);
STUBBED(iggy_compute_bounds);
// STUBBED(IggyConfigureBool);
// STUBBED(IggyConfigureVersionedBehavior);
STUBBED(iggy_convert_file);
STUBBED(iggy_copy_arraydata_GC);
STUBBED(iggy_core_destroy);
STUBBED(iggy_create_empty_bitmap);
STUBBED(iggy_create_from_memory);
STUBBED(iggy_create_movie_complete_GC);
STUBBED(iggy_create_movie_for_actionscript_object);
STUBBED(iggy_create_textfield);
STUBBED(IggyDebugBreakOnAS3Exception);
STUBBED(iggy__debug_configure_log);
// STUBBED(IggyDebugGetMemoryUseInfo);
// STUBBED(IggyDebugGetNumValueRef);
void iggy__debug_printf(const char *format, ...) {
#ifdef DEBUG
  va_list args;
  va_start(args, format);
  vprintf(format, args);
#endif
}
STUBBED(iggy_DebugSegments);
STUBBED(IggyDebugTexgen);
STUBBED(iggy_decode_image);
STUBBED(iggy_decode_swf_from_memory);
STUBBED(iggy_destroy_sprite);
STUBBED(iggy_destroy_sprite_attachments);
STUBBED(iggy_destroy_sprite_during_shutdown);
STUBBED(iggy_destroy_textfield_text);
STUBBED(iggy_direct_texture_deref);
STUBBED(iggy_direct_texture_rebuild);
STUBBED(iggy_discard_seek_queue);
// STUBBED(IggyDiscardVertexBufferCallback);
STUBBED(iggy_do_placement);
STUBBED(iggy_do_placeobject_GC);
STUBBED(iggy_do_playsound);
STUBBED(iggy_do_replace_text);
STUBBED(iggy_draw_batch);
STUBBED(iggy_draw_bevel);
STUBBED(iggy_draw_bitmap_raw);
STUBBED(iggy_draw_blur);
STUBBED(iggy_draw_buffered_rect);
STUBBED(iggy_draw_buffered_rect_would_flush);
STUBBED(iggy_draw_char);
STUBBED(iggy_draw_dropshadow);
STUBBED(iggy_draw_edittext);
STUBBED(iggy_draw_edittext_filters);
STUBBED(iggy_draw_filter_quad);
STUBBED(iggy_draw_one_displayobject);
STUBBED(iggy_draw_pixel_box);
STUBBED(iggy_draw_rectangle);
STUBBED(iggy_draw_rectangle_texgen);
STUBBED(iggy_draw_screen_rect);
STUBBED(iggy_draw_shape_raw);
STUBBED(iggy_draw_stroke_mesh);
STUBBED(iggy_draw_text);
STUBBED(iggy_draw_text_bitmap);
STUBBED(iggy_draw_text_border);
STUBBED(iggy_draw_text_cursor);
STUBBED(iggy_draw_tiles_begin);
STUBBED(iggy_dynamic_graphics_clear_cache);
STUBBED(iggy_edittext_char);
STUBBED(iggy_edittext_clear);
STUBBED(iggy_edittext_copy_utf16);
STUBBED(iggy_edittext_copy_utf8);
STUBBED(iggy_edittext_cut);
STUBBED(iggy_edittext_down);
STUBBED(iggy_edittext_drag);
STUBBED(iggy_edittext_keydown);
STUBBED(iggy_edittext_paste_utf16);
STUBBED(iggy_end_buffered_rects);
STUBBED(iggy_end_execution);
STUBBED(iggy_end_masking);
STUBBED(iggy_end_nested_draw);
STUBBED(iggy_error);
STUBBED(iggy_error_ex);
STUBBED(iggy_expand_creation_placeobjects);
// STUBBED(IggyFastTextFilterEffects);
STUBBED(iggy_find_delete_frames);
STUBBED(iggy_find_frame_label);
STUBBED(iggy_finish_creating_movie_GC);
STUBBED(iggy_flush_buffered_rects);
STUBBED(iggy_flush_direct_textures);
STUBBED(iggy_flush_installed_texture);
STUBBED(iggy_flush_seek_queue_GC);
STUBBED(iggy_flush_shape);
STUBBED(iggy_flush_textureinfo_for_iggyexp);
STUBBED(iggy_flush_triangulation_caches);
// STUBBED(IggyForceBitmapSmoothing);
STUBBED(iggy_free_align16);
STUBBED(iggy_free_as3_filters);
STUBBED(iggy_freedtoa);
STUBBED(iggy_free_graphics);
STUBBED(iggy_free_library_id);
STUBBED(iggy_free_shape_for_glyph);
STUBBED(iggy_free_textfield);
STUBBED(iggy_free_triangulation);
STUBBED(iggy_free_vbuf);
STUBBED(iggy_free_voice);
STUBBED(iggy_free_voice_if_done);
STUBBED(iggy_free_voice_memory);
// STUBBED(IggyGDrawFree);
STUBBED(iggy_gdraw_FreeTexture);
STUBBED(iggy_gdraw_FreeVertexBuffer);
// STUBBED(IggyGDrawSendWarning);
STUBBED(iggy_gdraw_stats);
STUBBED(iggy_gdraw_TryToLockTexture);
STUBBED(iggy_gdraw_TryToLockVertexBuffer);
STUBBED(iggy_gdraw_UnlockHandles);
// STUBBED(IggyGenericGetTextureResourceMetadata);
// STUBBED(IggyGenericInstallResourceFile);
// STUBBED(IggyGenericSetTextureFromResource);
STUBBED(iggy_get_bitmap_texture);
STUBBED(iggy_get_blitter);
STUBBED(iggy_get_blur_bounds);
STUBBED(iggy_get_bounds);
STUBBED(iggy_get_char_renderstate);
STUBBED(iggy_get_displacement);
STUBBED(iggy_get_export);
STUBBED(iggy_get_fill_style_texture);
STUBBED(iggy_get_glyph_for_codepoint);
STUBBED(iggy_get_glyph_metrics);
STUBBED(IggyGetInfo);
STUBBED(iggy_get_libnum);
STUBBED(iggy_get_library);
STUBBED(iggy_get_library_id);
STUBBED(iggy_get_ms_timer);
STUBBED(iggy_get_o2p);
STUBBED(iggy_get_o2w);
STUBBED(iggy_get_o2w_scroll);
STUBBED(iggy_get_path_value);
STUBBED(iggy_get_placeobject_size);
STUBBED(iggy_get_seconds_best_effort);
STUBBED(iggy_get_shape_for_glyph);
STUBBED(iggy_get_shape_stats);
STUBBED(iggy_get_symbol);
STUBBED(iggy_get_timezone_offset_in_minutes);
STUBBED(iggy_get_unsafe_glyph_for_codepoint);
STUBBED(iggy_glyph_is_empty);
STUBBED(iggy_gmtime_from_ms);
STUBBED(iggy_goto_frame_GC);
STUBBED(iggy_goto_frame_label_GC);
STUBBED(iggy_halt_voice);
STUBBED(iggy_hit_test_point);
STUBBED(iggy_iggyexp_char);
STUBBED(iggy_image_storage_get_current);
STUBBED(iggy_image_storage_next);
// STUBBED(IggyInit);
STUBBED(IggyInit_core);
STUBBED(iggy_initialized_main_movie_GC);
STUBBED(iggy_initialize_main_timeline_3d);
STUBBED(iggy_init_textfield);
STUBBED(iggy_init_texture_squareroot);
STUBBED(iggy_insert_movie_at_GC);
STUBBED(iggy_insert_movie_messages_GC);
// STUBBED(IggyInstallPerfmon);
STUBBED(iggy_invalid);
STUBBED(iggy_inverse_transform);
STUBBED(iggy_invert_matrix);
// STUBBED(IggyIsValueRefSameObjectAsTempRef);
// STUBBED(IggyIsValueRefSameObjectAsValuePath);
STUBBED(iggy_is_weak_ptr);
// STUBBED(IggyLibraryCreateFromMemory);
// STUBBED(IggyLibraryCreateFromMemoryUTF16);
// STUBBED(IggyLibraryDestroy);
// STUBBED(IggyLibraryFlushAll);
// STUBBED(IggyLibraryGetGeneric);
STUBBED(iggy_loadtime_translate16);
STUBBED(iggy_loadtime_translate8);
STUBBED(iggy_loadtime_translate_free);
STUBBED(iggy_lowlevel_set_xform);
STUBBED(iggy_lowlevel_set_xform_translation);
STUBBED(iggy_make_aa_texture);
STUBBED(iggy_make_empty_button);
STUBBED(iggy_make_empty_shape);
STUBBED(iggy_make_empty_sprite);
STUBBED(iggy_make_empty_textfield);
// STUBBED(IggyMakeEventActivate);
// STUBBED(IggyMakeEventChar);
// STUBBED(IggyMakeEventFocusGained);
// STUBBED(IggyMakeEventFocusLost);
// STUBBED(IggyMakeEventKey);
// STUBBED(IggyMakeEventMouseButton);
// STUBBED(IggyMakeEventMouseLeave);
// STUBBED(IggyMakeEventMouseMove);
// STUBBED(IggyMakeEventMouseWheel);
// STUBBED(IggyMakeEventNone);
// STUBBED(IggyMakeEventResize);
STUBBED(iggy_make_glow_gradient_texture);
STUBBED(iggy_make_gradient_texture);
STUBBED(iggy_make_linear_gradient_texture);
STUBBED(iggy_make_radial_gradient_texture);
STUBBED(iggy_mark_movie_dirty);
STUBBED(iggy_matrix_concatenate);
STUBBED(iggy_measure_cached_triangulation);
STUBBED(iggy_merge_bounds);
STUBBED(iggy_merge_bounds_or_set);
STUBBED(iggy_monitor_variable);
STUBBED(iggy_ms_from_gmtime);
STUBBED(iggy_ms_gmtime);
STUBBED(iggy_offset_clip_rect);
STUBBED(iggy_onesection_get_cached_triangulation);
STUBBED(iggy_outofmem_create);
STUBBED(iggy_platform_init);
STUBBED(iggy_play_adpcm);
STUBBED(iggy_player_flush_core);
STUBBED(iggy_play_framescript);
STUBBED(iggy_play_framescripts);
STUBBED(iggy_play_framescripts_complete);
STUBBED(iggy_play_mp3);
STUBBED(iggy_play_sound);
STUBBED(iggy_play_uncompressed);
STUBBED(iggy_play_voice);
STUBBED(iggy_poll_iggyexp);
STUBBED(iggy_polygonalize);
STUBBED(iggy_polygonalize_free);
STUBBED(iggy_predraw_edittext);
STUBBED(iggy_predraw_stroke_mesh);
STUBBED(iggy_rand);
STUBBED(iggy_random);
STUBBED(iggy_recompute_cull_rect);
STUBBED(iggy_remove_from_unparented);
STUBBED(iggy_remove_sprite);
STUBBED(iggy_reset_cursor_flash_state);
STUBBED(iggy_runtime_translate16);
STUBBED(iggy_runtime_translate_free);
STUBBED(iggy_seek_frame_deletes);
STUBBED(iggy_seek_frame_GC);
STUBBED(iggy_seek_frame_only_updates_GC);
STUBBED(iggy_send_display_tree);
STUBBED(iggy_send_draw_edittext_stats);
STUBBED(iggy_send_draw_text_stats);
STUBBED(iggy_send_error);
// STUBBED(IggySetAS3ExternalFunctionCallbackUTF16);
// STUBBED(IggySetAS3ExternalFunctionCallbackUTF8);
STUBBED(IggySetAudioLatency);
STUBBED(IggySetAudioMaxBufferTime);
STUBBED(iggy_set_bounds);
STUBBED(iggy_set_button_state);
STUBBED(iggy_setcolor_4f);
STUBBED(iggy_setcolor_4ub);
STUBBED(iggy_setcolor_4ub_cxf);
// STUBBED(IggySetCustomDrawCallback);
// STUBBED(IggySetDoubleClickTime);
STUBBED(iggy_set_focus_typed);
// STUBBED(IggySetGDraw);
// STUBBED(IggySetLanguage);
// STUBBED(IggySetLoadtimeTranslationFunction);
// STUBBED(IggySetLoadtimeTranslationFunctionUTF16);
// STUBBED(IggySetLoadtimeTranslationFunctionUTF8);
// STUBBED(iggy_set_mouseover_list);
// STUBBED(iggy_set_movie_defaults);
// STUBBED(iggy_set_movie_parent);
// STUBBED(IggySetRuntimeTranslationFunction);
// STUBBED(IggySetRuntimeTranslationFunctionUTF16);
// STUBBED(IggySetRuntimeTranslationFunctionUTF8);
// STUBBED(IggySetTextCursorFlash);
// STUBBED(IggySetTextCursorPixelWidth);
// STUBBED(iggy_set_textfield_htmltext);
// STUBBED(iggy_set_textfield_text);
// STUBBED(IggySetTextfieldTranslationFunctionUTF16);
// STUBBED(IggySetTextfieldTranslationFunctionUTF8);
// STUBBED(IggySetTextureSubstitutionCallbacks);
// STUBBED(IggySetTextureSubstitutionCallbacksUTF8);
// STUBBED(IggySetTraceCallbackUTF16);
// STUBBED(IggySetTraceCallbackUTF8);
STUBBED(iggy_setup_3d_transform);
STUBBED(iggy_setup_bitmap_renderstate);
STUBBED(iggy_setup_bitmap_texture_renderstate);
STUBBED(iggy_setup_fill_style);
// STUBBED(IggySetValueRefLimit);
// STUBBED(IggySetWarningCallback);
STUBBED(iggy_shape_has_class);
STUBBED(iggy_shape_hit_test);
STUBBED(IggyShutdown);
STUBBED(IggyShutdown_core);
STUBBED(iggy_simple_mix);
STUBBED(iggy_simpmix_init_info);
STUBBED(iggy_simpmix_set_matrix);
STUBBED(iggy_simpmix_set_volume);
STUBBED(iggy_sound_get_position);
STUBBED(iggy_sound_set_driver);
STUBBED(iggy_sound_shutdown);
STUBBED(iggy_start_buffered_rects);
STUBBED(iggy_start_masking);
STUBBED(iggy_start_nested_draw);
STUBBED(iggy_stroke_path);
STUBBED(iggy_stroke_path_for_antialiasing);
STUBBED(iggy_stroke_path_free);
STUBBED(iggy_subtract_sound_client);
STUBBED(iggy_sync_check_end);
// STUBBED(iggy_sync_check_fromdisk);
// STUBBED(iggy_sync_check_todisk);
STUBBED(iggy_tesselate_and_triangulate);
STUBBED(iggy_textfield_compute_info);
STUBBED(iggy_textfield_objectspace_bounds);
STUBBED(iggy_textfield_reflow);
STUBBED(iggy_textfield_select_all);
STUBBED(iggy_textfield_set_height);
STUBBED(iggy_textfield_set_width);
STUBBED(iggy_textfield_translate16);
STUBBED(iggy_textfield_translate_free);
STUBBED(iggy_textfield_update_styles);
// STUBBED(IggyTextureSubstitutionFlush);
// STUBBED(IggyTextureSubstitutionFlushAll);
STUBBED(iggy_tmDynamicStringUTF16);
STUBBED(iggy_transform);
STUBBED(iggy_triangulate);
STUBBED(iggy_triangulate_cached);
STUBBED(iggy_triangulate_compute_flip);
STUBBED(iggy_tt_CompareUTF8toUTF16_bigendian);
STUBBED(iggy_tt_FindGlyphIndex);
STUBBED(iggy_tt_FlattenCurves);
STUBBED(iggy_tt_FreeBitmap);
STUBBED(iggy_tt_FreeShape);
STUBBED(iggy_tt_GetBakedQuad);
STUBBED(iggy_tt_GetCodepointBitmap);
STUBBED(iggy_tt_GetCodepointBitmapBox);
STUBBED(iggy_tt_GetCodepointBox);
STUBBED(iggy_tt_GetCodepointHMetrics);
STUBBED(iggy_tt_GetCodepointKernAdvance);
STUBBED(iggy_tt_GetCodepointShape);
STUBBED(iggy_tt_GetGlyphBitmap);
STUBBED(iggy_tt_GetGlyphBitmapBox);
STUBBED(iggy_tt_GetGlyphBox);
STUBBED(iggy_tt_GetGlyphHMetrics);
STUBBED(iggy_tt_GetGlyphKernAdvance);
STUBBED(iggy_tt_GetGlyphShape);
STUBBED(iggy_tt_IsGlyphEmpty);
STUBBED(iggy_tt_MakeCodepointBitmap);
STUBBED(iggy_tt_MakeGlyphBitmap);
STUBBED(iggy_tt_Rasterize);
STUBBED(iggy_tt_ScaleForMappingEmToPixels);
STUBBED(iggy_tt_ScaleForPixelHeight);
STUBBED(iggy_tt_SetUserData);
STUBBED(iggy_uncaught_exception_warning);
STUBBED(iggy_update_button);
STUBBED(iggy_update_root_scale);
STUBBED(iggy_update_voice);
// STUBBED(IggyUseExplorer);
// STUBBED(IggyUseTelemetry);
// STUBBED(IggyUseTmLite);
// STUBBED(IggyValueGetArrayLengthRS);
// STUBBED(IggyValueGetBooleanRS);
// STUBBED(IggyValueGetF32RS);
// STUBBED(IggyValueGetF64RS);
// STUBBED(IggyValueGetS32RS);
// STUBBED(IggyValueGetStringUTF16RS);
// STUBBED(IggyValueGetStringUTF8RS);
// STUBBED(IggyValueGetTypeRS);
// STUBBED(IggyValueGetU32RS);
// STUBBED(IggyValueGetUserDataRS);
// STUBBED(IggyValuePathFromRef);
// STUBBED(IggyValuePathMakeArrayRef);
// STUBBED(IggyValuePathMakeNameRef);
// STUBBED(IggyValuePathMakeNameRefFast);
// STUBBED(IggyValuePathSetArrayIndex);
// STUBBED(IggyValuePathSetName);
// STUBBED(IggyValuePathSetParent);
// STUBBED(IggyValueRefCheck);
// STUBBED(IggyValueRefCreateArray);
// STUBBED(IggyValueRefCreateEmptyObject);
// STUBBED(IggyValueRefFree);
// STUBBED(IggyValueRefFromPath);
// STUBBED(IggyValueRefFromTempRef);
// STUBBED(IggyValueSetBooleanRS);
// STUBBED(IggyValueSetF32RS);
// STUBBED(IggyValueSetF64RS);
// STUBBED(IggyValueSetS32RS);
// STUBBED(IggyValueSetStringUTF16RS);
// STUBBED(IggyValueSetStringUTF8RS);
// STUBBED(IggyValueSetU32RS);
// STUBBED(IggyValueSetUserDataRS);
// STUBBED(IggyValueSetValueRefRS);
STUBBED(iggy_verify_container);
STUBBED(iggy_vsend_error);
// STUBBED(IggyWaitOnFence);
STUBBED(iggy_zero_movie_state);
