#!/bin/sh
# stub.sh makes a H file full of stubs
# based on the symbols provided by an .so file

if [ -z "$1" ]; then
    echo "Usage: $0 <library.so>"
    exit 1
fi
out="stub.h"
>"$out"

symbols=$(nm -gD "$1" | grep ' T ')
count=$(echo "$symbols" | wc -l)

# Stub macro warns when a stubbed function is called
echo "// Generated by stub.sh
#ifndef STUBBED
#include <stdio.h>
#define STUBBED(fun) inline void fun() {printf(\"[WARN]: %s is unimplemented\n\", #fun);}
#endif
" >>"$out"

counter=0
sp="/-\|"

# Hide cursor
# prevents animated cursors from hiding text output
echo -e "\e[?25l"

while IFS= read -r line; do
    name=$(echo "$line" | awk '{print $3}')
    if [ -n "$name" ]; then
        echo " $name"
        echo "STUBBED($name);">>"$out"
    fi
    counter=$((counter + 1))
    progress=$((counter * 100 / count))
    echo -ne "\r\b${sp:i++%${#sp}:1} Making stubs... $progress% - Stubbing :"
done <<<"$symbols"

# Unhide cursor
echo -ne " Completed\n\e[?25h"
